[3.1.818] NOTES:

diff --git a/sh/focus-ndi b/sh/focus-ndi
--- a/sh/focus-ndi
+++ b/sh/focus-ndi
@@ -9,8 +9,6 @@ set -e
 
 # xcompmgr -d :0 -fFCnR &
 # sleep 1
-
-FADE_TIME=0.05
     
 # activateWindow() {
 #     if [[ -z "$WINDOW_ID" ]]; then
@@ -28,76 +26,159 @@ FADE_TIME=0.05
 #     sleep 1
 # }
 
-fadeInVolume() {
-    current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
-    target=255
-
-    if [ "$current" -lt "$target" ]; then
-        while [ "$current" -lt "$target" ]; do
-            current=$((current + 5))
-            [ "$current" -gt "$target" ] && current=$target
-            amixer set PCM "$current" >/dev/null
-            sleep $FADE_TIME
-        done
-    else
-        while [ "$current" -gt "$target" ]; do
-            current=$((current - 5))
-            [ "$current" -lt "$target" ] && current=$target
-            amixer set PCM "$current" >/dev/null
-            sleep $FADE_TIME
-        done
-    fi
-}
-fadeOutVolume() {
-    current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
-    target=0
-
-    if [ "$current" -lt "$target" ]; then
-        while [ "$current" -lt "$target" ]; do
-            current=$((current + 5))
-            [ "$current" -gt "$target" ] && current=$target
-            amixer set PCM "$current" >/dev/null
-            sleep $FADE_TIME
-        done
-    else
-        while [ "$current" -gt "$target" ]; do
-            current=$((current - 5))
-            [ "$current" -lt "$target" ] && current=$target
-            amixer set PCM "$current" >/dev/null
-            sleep $FADE_TIME
-        done
-    fi
-}
+FADE_TIME=0.5
 
 activateWindow() {
-    WINDOW_ID="$(xdotool search --class 'gstreamer' | head -n 1)"
+    WINDOW_ID="$(xdotool search --onlyvisible --class 'chromium' | head -n 1)"
+    # NDI_WINDOW_ID="$(xdotool search --class 'gstreamer' | head -n 1)"
 
     if [[ -z "$WINDOW_ID" ]]; then
         echo "$1 FAILED to find visible window."
         echo "---------"
         echo "[Results]"
-        echo "$(xdotool search --class 'gstreamer')"
+        echo "$(xdotool search --onlyvisible --class 'chromium')"
         echo "---------"
         exit 1
     fi
 
-    xdotool windowminimize $WINDOW_ID
-    sleep 0.5
+    # picom -f -D 6 -i 0 --backend xrender --force-win-blend --no-fading-openclose --realtime --no-vsync &
+    # picom -f -D 6 -i 0 --backend xrender --force-win-blend --realtime --vsync &
+    # picom --config "${HOME}/.config/picom/picom.conf" &
+    
+    # sleep 2
+
+    
+    # xdotool windowminimize $WINDOW_ID
+    # sleep 0.5
 
     # xdotool windowraise $WINDOW_ID
     # sleep 0.5
 
-    xdotool windowactivate $WINDOW_ID
-    sleep 0.5
+    # xdotool windowactivate $WINDOW_ID --sync
+    # sleep 0.5
+}
+
+fadeIn() {
+    local current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
+    local target=100
+
+    if [ "$current" -lt "$target" ]; then
+        while [ "$current" -lt "$target" ]; do
+            current=$((current + 1))
+            [ "$current" -gt "$target" ] && current=$target
+            amixer set PCM "${current}%" >/dev/null
+            picom-trans -w $WINDOW_ID $current >/dev/null
+            sleep $FADE_TIME
+        done
+    else
+        while [ "$current" -gt "$target" ]; do
+            current=$((current - 1))
+            [ "$current" -lt "$target" ] && current=$target
+            amixer set PCM "${current}%" >/dev/null
+            picom-trans -w $WINDOW_ID $current >/dev/null
+            sleep $FADE_TIME
+        done
+    fi
+}
+fadeOut() {
+    local current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
+    local target=0
+
+    if [ "$current" -lt "$target" ]; then
+        while [ "$current" -lt "$target" ]; do
+            current=$((current + 1))
+            [ "$current" -gt "$target" ] && current=$target
+            amixer set PCM "${current}%" >/dev/null
+            picom-trans -w $WINDOW_ID $current >/dev/null
+            sleep $FADE_TIME
+        done
+    else
+        while [ "$current" -gt "$target" ]; do
+            current=$((current - 1))
+            [ "$current" -lt "$target" ] && current=$target
+            amixer set PCM "${current}%" >/dev/null
+            picom-trans -w $WINDOW_ID $current >/dev/null
+            sleep $FADE_TIME
+        done
+    fi
 }
 
 # Start
 activateWindow
-
-fadeInVolume
-
-if ! [[ -z "$(pgrep picom)" ]]; then
-    killall picom >/dev/null 2>&1
-fi
-
+fadeOut
+# killall picom
 exit 0
+
+# fadeInVolume() {
+#     current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
+#     target=255
+
+#     if [ "$current" -lt "$target" ]; then
+#         while [ "$current" -lt "$target" ]; do
+#             current=$((current + 5))
+#             [ "$current" -gt "$target" ] && current=$target
+#             amixer set PCM "$current" >/dev/null
+#             sleep $FADE_TIME
+#         done
+#     else
+#         while [ "$current" -gt "$target" ]; do
+#             current=$((current - 5))
+#             [ "$current" -lt "$target" ] && current=$target
+#             amixer set PCM "$current" >/dev/null
+#             sleep $FADE_TIME
+#         done
+#     fi
+# }
+# fadeOutVolume() {
+#     current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
+#     target=0
+
+#     if [ "$current" -lt "$target" ]; then
+#         while [ "$current" -lt "$target" ]; do
+#             current=$((current + 5))
+#             [ "$current" -gt "$target" ] && current=$target
+#             amixer set PCM "$current" >/dev/null
+#             sleep $FADE_TIME
+#         done
+#     else
+#         while [ "$current" -gt "$target" ]; do
+#             current=$((current - 5))
+#             [ "$current" -lt "$target" ] && current=$target
+#             amixer set PCM "$current" >/dev/null
+#             sleep $FADE_TIME
+#         done
+#     fi
+# }
+
+# activateWindow() {
+#     CHROMIUM_WINDOW_ID="$(xdotool search --onlyvisible --class 'chromium' | head -n 1)"
+#     NDI_WINDOW_ID="$(xdotool search --class 'gstreamer' | head -n 1)"
+
+#     if [[ -z "$NDI_WINDOW_ID" ]]; then
+#         echo "$1 FAILED to find visible window."
+#         echo "---------"
+#         echo "[Results]"
+#         echo "$(xdotool search --class 'gstreamer')"
+#         echo "---------"
+#         exit 1
+#     fi
+
+#     # xdotool windowraise $NDI_WINDOW_ID
+#     # sleep 0.5
+
+#     xdotool windowactivate $NDI_WINDOW_ID --sync
+
+#     xdotool windowminimize $CHROMIUM_WINDOW_ID --sync
+#     # sleep 0.5
+# }
+
+# # Start
+# fadeInVolume
+
+# activateWindow
+
+# if ! [[ -z "$(pgrep picom)" ]]; then
+#     killall picom >/dev/null 2>&1
+# fi
+
+# exit 0
